
/*  © Copyright CERN, 2015. All rights not expressly granted are reserved.

    The stub of this file was generated by quasar (https://github.com/quasar-team/quasar/)

    Quasar is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public Licence as published by
    the Free Software Foundation, either version 3 of the Licence.
    Quasar is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public Licence for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with Quasar.  If not, see <http://www.gnu.org/licenses/>.


 */


#ifndef __DOnlineConfigValidator__H__
#define __DOnlineConfigValidator__H__

#include <Base_DOnlineConfigValidator.h>

namespace Device
{

class
    DOnlineConfigValidator
    : public Base_DOnlineConfigValidator
{

public:
    /* sample constructor */
    explicit DOnlineConfigValidator (
        const Configuration::OnlineConfigValidator& config,
        Parent_DOnlineConfigValidator* parent
    ) ;
    /* sample dtr */
    ~DOnlineConfigValidator ();

    /* delegators for
    cachevariables and sourcevariables */


    /* delegators for methods */
    UaStatus callValidate (
        std::vector<UaString>& details,
        OpcUa_Boolean& passed
    ) ;

private:
    /* Delete copy constructor and assignment operator */
    DOnlineConfigValidator( const DOnlineConfigValidator& other );
    DOnlineConfigValidator& operator=(const DOnlineConfigValidator& other);

    // ----------------------------------------------------------------------- *
    // -     CUSTOM CODE STARTS BELOW THIS COMMENT.                            *
    // -     Don't change this comment, otherwise merge tool may be troubled.  *
    // ----------------------------------------------------------------------- *

public:

private:



};

}

#endif // __DOnlineConfigValidator__H__