
/*  © Copyright CERN, 2015. All rights not expressly granted are reserved.

    The stub of this file was generated by quasar (https://github.com/quasar-team/quasar/)

    Quasar is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public Licence as published by
    the Free Software Foundation, either version 3 of the Licence.
    Quasar is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public Licence for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with Quasar.  If not, see <http://www.gnu.org/licenses/>.


 */


#ifndef __DRpdo__H__
#define __DRpdo__H__

#include <Base_DRpdo.h>

namespace Device
{

class
    DRpdo
    : public Base_DRpdo
{

public:
    /* sample constructor */
    explicit DRpdo (
        const Configuration::Rpdo& config,
        Parent_DRpdo* parent
    ) ;
    /* sample dtr */
    ~DRpdo ();

    /* delegators for
    cachevariables and sourcevariables */


    /* delegators for methods */

private:
    /* Delete copy constructor and assignment operator */
    DRpdo( const DRpdo& other );
    DRpdo& operator=(const DRpdo& other);

    // ----------------------------------------------------------------------- *
    // -     CUSTOM CODE STARTS BELOW THIS COMMENT.                            *
    // -     Don't change this comment, otherwise merge tool may be troubled.  *
    // ----------------------------------------------------------------------- *

public:
    std::vector<uint8_t>& getCache() { return m_cache; }
    void propagateCache();

private:
    std::vector<uint8_t> m_cache;



};

}

#endif // __DRpdo__H__