
/*  © Copyright CERN, 2015. All rights not expressly granted are reserved.

    The stub of this file was generated by quasar (https://github.com/quasar-team/quasar/)

    Quasar is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public Licence as published by
    the Free Software Foundation, either version 3 of the Licence.
    Quasar is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public Licence for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with Quasar.  If not, see <http://www.gnu.org/licenses/>.


 */


#ifndef __DSdoSameIndexGroup__H__
#define __DSdoSameIndexGroup__H__

#include <Base_DSdoSameIndexGroup.h>

namespace Device
{

class
    DSdoSameIndexGroup
    : public Base_DSdoSameIndexGroup
{

public:
    /* sample constructor */
    explicit DSdoSameIndexGroup (
        const Configuration::SdoSameIndexGroup& config,
        Parent_DSdoSameIndexGroup* parent
    ) ;
    /* sample dtr */
    ~DSdoSameIndexGroup ();

    /* delegators for
    cachevariables and sourcevariables */


    /* delegators for methods */

private:
    /* Delete copy constructor and assignment operator */
    DSdoSameIndexGroup( const DSdoSameIndexGroup& other );
    DSdoSameIndexGroup& operator=(const DSdoSameIndexGroup& other);

    // ----------------------------------------------------------------------- *
    // -     CUSTOM CODE STARTS BELOW THIS COMMENT.                            *
    // -     Don't change this comment, otherwise merge tool may be troubled.  *
    // ----------------------------------------------------------------------- *

public:
    uint16_t index() const { return m_index; }
    void propagateIndex();

private:
    const uint16_t m_index;



};

}

#endif // __DSdoSameIndexGroup__H__