
/*  © Copyright CERN, 2015. All rights not expressly granted are reserved.

    The stub of this file was generated by quasar (https://github.com/quasar-team/quasar/)

    Quasar is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public Licence as published by
    the Free Software Foundation, either version 3 of the Licence.
    Quasar is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public Licence for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with Quasar.  If not, see <http://www.gnu.org/licenses/>.


 */


#include <Configuration.hxx> // TODO; should go away, is already in Base class for ages

#include <DSdoItem.h>
#include <ASSdoItem.h>

#include <DSdoSameIndexGroup.h>
#include <DNode.h>
#include <DRoot.h>
#include <DGlobalSettings.h>
#include <DBus.h>

#include <ValueMapper.h>
#include <Logging.hpp>



using namespace Logging;

namespace Device
{
// 1111111111111111111111111111111111111111111111111111111111111111111111111
// 1     GENERATED CODE STARTS HERE AND FINISHES AT SECTION 2              1
// 1     Users don't modify this code!!!!                                  1
// 1     If you modify this code you may start a fire or a flood somewhere,1
// 1     and some human being may possible cease to exist. You don't want  1
// 1     to be charged with that!                                          1
// 1111111111111111111111111111111111111111111111111111111111111111111111111






// 2222222222222222222222222222222222222222222222222222222222222222222222222
// 2     SEMI CUSTOM CODE STARTS HERE AND FINISHES AT SECTION 3            2
// 2     (code for which only stubs were generated automatically)          2
// 2     You should add the implementation but dont alter the headers      2
// 2     (apart from constructor, in which you should complete initializati2
// 2     on list)                                                          2
// 2222222222222222222222222222222222222222222222222222222222222222222222222

/* sample ctr */
DSdoItem::DSdoItem (
    const Configuration::SdoItem& config,
    Parent_DSdoItem* parent
):
    Base_DSdoItem( config, parent)

    /* fill up constructor initialization list here */
{
    /* fill up constructor body here */
    m_subIndex = config.subIndex(); // perhaps we should optimize it ;-)
}

/* sample dtr */
DSdoItem::~DSdoItem ()
{
}

/* delegates for cachevariables */


/* ASYNCHRONOUS !! */
UaStatus DSdoItem::readValue (
    UaVariant& value,
    UaDateTime& sourceTime
)
{
    /* Is it actually allowed to read this SDO? */
    if (access().find("R") == std::string::npos)
    {
        LOG(Log::ERR) << wrapId(getFullName()) << ": SDO read was denied because it is denied in the configuration.";
        return OpcUa_BadUserAccessDenied;
    }
    /* Not in spy mode? */
    if (getParent()->getParent()->getParent()->isInSpyMode())
    {
        LOG(Log::ERR) << wrapId(getFullName()) << ": SDO read was denied because the bus is currently in the spy mode.";
        return OpcUa_BadOutOfService;
    }

    std::vector<unsigned char> readData;
    bool status = getParent()->getParent()->sdoEngine().readExpedited(
        getFullName(),
        getParent()->index(), 
        m_subIndex, 
        readData, 
        1000.0 * Device::DRoot::getInstance()->globalsettings()->expeditedSdoTimeoutSeconds());
    if (!status)
        return OpcUa_BadOutOfService; // maybe we should return uastatus right away
    sourceTime = UaDateTime::now();
    LOG(Log::TRC) << wrapId(getFullName()) << "SDO transaction finished, performing value mapping now";
    try
    {
        value = ValueMapper::extractFromBytesIntoVariant(&readData[0], readData.size(), dataType(), 0, booleanFromBit());
    }
    catch(const std::exception& e)
    {
        LOG(Log::ERR) << e.what() << "(note: dataType was " << dataType() << ")";
        return OpcUa_Bad;
    }
    return OpcUa_Good;
}
/* ASYNCHRONOUS !! */
UaStatus DSdoItem::writeValue (
    UaVariant& value
)
{
    /* Is it actually allowed to write this SDO? */
    if (access().find("W") == std::string::npos)
    {
        LOG(Log::ERR) << wrapId(getFullName()) << ": SDO write was denied because it is denied in the configuration.";
        return OpcUa_BadUserAccessDenied;
    }

    /* Not in spy mode? */
    if (getParent()->getParent()->getParent()->isInSpyMode())
    {
        LOG(Log::ERR) << wrapId(getFullName()) << ": SDO read was denied because the bus is currently in the spy mode.";
        return OpcUa_BadOutOfService;
    }

    // Synchronization: use quasar's made mutex:
    std::lock_guard<boost::mutex> lock (getParent()->getParent()->getLock());

    std::vector<uint8_t> bytes = ValueMapper::packVariantToBytes(value, dataType());
    bool status = getParent()->getParent()->sdoEngine().writeExpedited(
        getFullName(),
        getParent()->index(), 
        m_subIndex, 
        bytes, 
        1000.0 * Device::DRoot::getInstance()->globalsettings()->expeditedSdoTimeoutSeconds());    
    return status ? OpcUa_Good : OpcUa_Bad;
}

/* delegators for methods */

// 3333333333333333333333333333333333333333333333333333333333333333333333333
// 3     FULLY CUSTOM CODE STARTS HERE                                     3
// 3     Below you put bodies for custom methods defined for this class.   3
// 3     You can do whatever you want, but please be decent.               3
// 3333333333333333333333333333333333333333333333333333333333333333333333333

}